version: '3.8'

services:
  gecko:
    build: ./gecko
    container_name: price-api
    networks:
      - price_service
    ports:
      - '4004:4004'
    volumes:
      - ../dockerdata/gecko:/data

networks:
  price_service:
volumes:
  dockerdata:
